[nfs]
172.31.92.121 ansible_ssh_user='ec2-user'

[webservers]
172.31.91.244 ansible_ssh_user='ec2-user'
172.31.85.139 ansible_ssh_user='ec2-user'

[db]
172.31.91.61 ansible_ssh_user='ubuntu' 

[lb]
172.31.86.110 ansible_ssh_user='ubuntu'
